.PHONY: clean All

All:
	@echo "----------Building project:[ Alarm_Controller - Debug ]----------"
	@cd "Alarm_Controller" && "$(MAKE)" -f  "Alarm_Controller.mk" && "$(MAKE)" -f  "Alarm_Controller.mk" PostBuild
clean:
	@echo "----------Cleaning project:[ Alarm_Controller - Debug ]----------"
	@cd "Alarm_Controller" && "$(MAKE)" -f  "Alarm_Controller.mk" clean
